# ESP32-P4-JC1060P470
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/JonnyKreng/HomeCockpit
    file: package.yaml
    refresh: 1sec
