packages:
  device: !include device/device.yaml
  sensors: !include device/sensors.yaml
  lvgl: !include device/lvgl.yaml
  time: !include addon/time.yaml
  backlight: !include addon/backlight.yaml
  network: !include addon/network.yaml
  fonts: !include assets/fonts.yaml
  icons: !include assets/icons.yaml
  global-theme: !include theme/global.yaml
  button-theme: !include theme/button.yaml
  container-theme: !include theme/container.yaml
  chart: !include addon/solar-chart/solar-chart.yaml
  weather: !include addon/weather.yaml
  people: !include addon/people.yaml
  car: !include addon/car.yaml
  heating: !include addon/heating.yaml
