substitutions:
  button_on_color: $heighlight_color
  button_text_color: $text_color
  button_control_color: $primary_color
  button_height: $widget_height
  button_width: $widget_width
  button_padding: $widget_padding
  button_radius: $widget_radius

lvgl:
  style_definitions:
    - id: control
      bg_color: $button_control_color

    - id: thermostat_ctrl_btn
      width: 52px
      height: 44px
      radius: $widget_radius
      bg_color: $primary_color
      pad_all: 6px
      shadow_width: 0
      border_width: 0

  theme:
    arc:
      arc_color: $heighlight_color
      arc_width: 8
      arc_rounded: true
      indicator:
        arc_color: $heighlight_color
        arc_width: 8
        arc_rounded: true
      knob:
        bg_color: $heighlight_color
        radius: 100%
        pad_all: 6px
      main:
        arc_color: $primary_color
        arc_width: 8


    dropdown:
      bg_color: $primary_color
      text_color: $text_color
      border_color: $heighlight_color
      border_width: 1
      radius: $widget_radius
      text_font: clockbar_font

    dropdown_list:
      bg_color: $primary_color
      text_color: $text_color
      border_color: $heighlight_color
      border_width: 1
      radius: $widget_radius

    button:
      text_font: label_font
      scroll_on_focus: false
      radius: $button_radius
      width: $button_width
      height: $button_height
      pad_all: $button_padding
      shadow_width: 0
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
