esphome:
  includes:
    - addon/solar-chart.h
    - addon/theme.h
  on_boot:
    then:
      - delay: 1sec
      - lambda: |-
            draw_chart(id(overview_tab)/*.obj*/);

globals:
  # Define a global variable as a vector with type float.
  - id: chart_values
    type: std::vector<float>

interval:
  - interval: 300s
    startup_delay: 10sec
    then:
      - lambda: |-
          float value = 0;
          int counter = id(chart_values).size();
          for(int i = 0; i < counter; i++) {
            value += id(chart_values).back();
            id(chart_values).pop_back();
          }
          float average = value / counter;
          ESP_LOGD("Interval", "Average is %f, count is %i", average, counter); 
          update_chart(average);

# interval:
#   - interval: 0.1s
#     startup_delay: 2sec
#     then:
#       - lambda: |-

#           static float value = 0;
#           update_chart(sin(value/4.0) * 400 + 400);
#           value += 0.1;

sensor:
  - platform: homeassistant
    entity_id: sensor.steckdose_nr_3_power
    force_update: True
    id: solar_power
    on_value:
      lambda: |-
        id(chart_values).insert(id(chart_values).begin(), x);
        ESP_LOGD("Interval", "Pushed value to vector %f", x); 